DBO-8 Added api endpoints for User Posts
Dubble-bubble-original/engg4000 pull request #32
Opened 2021-11-03 21:03 UTC by JoaoPontes98

This includes api.raml docs, the addition of middleware to app.js, and updates to routes.js. I also made some syntax changes in the api.js that the linter was yelling at me to fix.

As you can see, these endpoints only allow for getting/deleting 1 post at a time. I didn't add a getAllUserposts() endpoint since I wasn't sure if it was necessary or not. If you guys think it needs to be added, I can whip it up real quick.

If you have more suggestions for response codes to add, please let me know.

2021-11-03 21:31 UTC, nathanielcaron commented
Awesome work @JoaoPontes98! 🚀

2021-11-04 13:39 UTC, fredy20501 reviewed
Nice work! 👍

2021-11-04 13:39 UTC, fredy20501 commented on Service/api/api.js
> +/* eslint-disable no-underscore-dangle */
We might as well disable this rule globally instead of doing it for each file.

Just add this to the `.eslintrc.json` file in the "rules" portion:
```
"no-underscore-dangle": [ "off" ]
```
(then you should be able to remove this comment and the linter should not care)

2021-11-04 13:39 UTC, fredy20501 commented on Service/api/api.js
> +    author: req.body.author,
The front end will not give you an author object but just the name and avatar image url. You'll need to create a user first using that given name & avatar image and then use that to create the post.

2021-11-04 13:39 UTC, fredy20501 commented on Service/api/api.js
> +    access_key: req.body.access_key
The access key will not be given by the frontend, the backend should be the one generating it and making sure it is unique (can double-check that it is unique by searching the db to see if another post already has the same access key).
You have already done a lot of work so writing the function to generate & verify access-keys could be done in another ticket.

2021-11-04 13:39 UTC, fredy20501 commented on Service/api/api.raml
> +      data_created:
Little typo 😉 
```suggestion
      date_created:
```

2021-11-04 15:10 UTC, fredy20501 commented on Service/api/api.js
> +    author: req.body.author,
Like Nathaniel said during our meeting, creating the user will be done in a separate function so you don't have to worry about this for now.

2021-11-06 14:39 UTC, fredy20501 commented on Service/api/api.js
> +      return res.status(401).send('Client access-key does NOT match the user post.');
We have to be careful returning status code 401 since that's the one used to signify an invalid auth token. You should consider changing this return code to something different or changing the status code for an invalid auth token so it is different.

2021-11-06 15:49 UTC, sahilsaini432 requested changes

2021-11-06 17:32 UTC, JoaoPontes98 commented on Service/api/api.js
> +  UserPost.findById(req.params.id)
Yeah it's for getting posts from the db.

2021-11-06 18:05 UTC, fredy20501 commented on Service/api/api.js
> +// eslint-disable-next-line consistent-return
We shouldn't disable linting for individual files/functions since the whole point of a linter is for **all** of our code to be consistent and follow all of the same rules. If you really think that an eslint rule is not appropriate for us, disable it globally. Otherwise, just change your code to make it work.

In this case, you can just replace `next()` with `return next()` to satisfy the linter. 
(you can google the eslint error to understand what it is expecting: e.g., [eslint consistent-return](https://eslint.org/docs/rules/consistent-return))

2021-11-06 18:08 UTC, fredy20501 commented on Service/api/api.js
> +    access_key: req.body.access_key
I added a ticket on trello for implementing this function.

2021-11-06 18:10 UTC, JoaoPontes98 commented on Service/api/api.js
> +// eslint-disable-next-line consistent-return
Yeah, that was definitely a lazy approach of me going about it, my bad. I didn't realize `return next()` was possible.

Should be fixed now with the latest commit.

2021-11-06 19:48 UTC, fredy20501 approved these changes
Awesome! 💯

2021-11-06 20:52 UTC, sahilsaini432 approved these changes

2021-11-06 20:53 UTC, sahilsaini432 approved these changes
Nice Work 👍

2021-11-07 13:58 UTC, fredy20501 commented
Manual testing of the API endpoints done with Postman. Steps:
1. Got token using /auth endpoint (used it for all requests).
2. Got a userPost using the /userpost/{id} GET endpoint (got the ID from MongoDB).
3. Created a userPost using the /userpost POST endpoint (fails when required fields missing, as expected).
4. Delete a userPost using the /userpost/{id} DELETE endpoint (fails when access-key not given in body or not match, as expected).

2021-11-07 14:01 UTC, merged