DBO-9 Added put endpoint for /userpost/:id, as well as get /userposts
Dubble-bubble-original/engg4000 pull request #35
Opened 2021-11-08 14:50 UTC by JoaoPontes98

How to update a userpost:
1.  Provide a .json object in the body with a single field called `update`. 
2.  Inside the `update` field, include whatever userpost properties you wish to update and the new data. Ex `{'update' : {'title':'new title'}}`
3. Send the put request to /userpost/:<doc_id>

How to get userposts:
1.  (Optional) include a filter in the body to return all userposts that match the filter. Ex `{filter: {authorID: <Auth_ID>}}`. If no filter is provided, all userposts will be returned
2.  Send the get request to /userposts

You will also notice some changes to the schema. Since this was to create a put endpoint, I made some of the fields immutable so that they can't be changed once the document has been created.

2021-11-08 15:31 UTC, nathanielcaron commented on Service/api/api.raml
> +    put:
Typically, if the `PUT` method is used, then the entire entity should be provided in the body of the request.
If only certain properties are provided, then the `PATCH` method should be used.

https://rapidapi.com/blog/put-vs-patch/

2021-11-08 18:26 UTC, fredy20501 commented on Service/api/api.js
> +      }
I'm not sure if we should consider no result as an error. We could just return an empty array/object instead (or maybe just return `docs` no matter what).

This decision will determine what the frontend needs to do. Either (a) check for status 406 and have a special case when empty or (b) check the length of the result and have a special case for that. 
Personally, I prefer (b) since I think we would still check the length of the result regardless, but it's up for debate.

2021-11-08 18:26 UTC, fredy20501 commented on Service/api/api.js
> +      }
Also, why do you check if the filter is not empty (`filter !== {}`)? (why is it only an error if the filter is not empty?)

2021-11-08 19:14 UTC, JoaoPontes98 commented on Service/api/api.js
> +      }
My thinking behind checking this was 'If there is a field in the filter that yields no results, then that means it's a bad filter and the developer should know.' But yeah looking back at it now, the logic is overly specific since just checking the length should be good enough for that.

I also agree that just sending docs would make it easier for programming the front-end. I'll be sure to remove this error.

2021-11-08 19:19 UTC, JoaoPontes98 commented on Service/api/api.raml
> +    put:
You guys cool with this being a PATCH instead then? I could quickly fix the raml/router.js to use PATCH.

Or is it best practice to have this act as PUT? That would involve tweaking the endpoint a bit but not much work at all.

2021-11-08 19:20 UTC, fredy20501 commented on Service/api/api.raml
> +    put:
I'm good with just changing it to PATCH. (given the planned functionality of our app I don't think we'll ever use this endpoint anyway)

2021-11-11 21:55 UTC, JoaoPontes98 commented
I added the access_key generation in the CREATE. I also changed the delete endpoint to instead use the access key in the parameters instead of the document ID. Since we were never using the document ID to find the doc to delete, I thought this way made more sense.

2021-11-12 21:56 UTC, fredy20501 approved these changes
Nice work! 👍

2021-11-12 23:07 UTC, fredy20501 requested changes
Found issues during testing.

2021-11-12 23:07 UTC, fredy20501 commented on Service/api/api.js
> +};
I tried testing these endpoints with Postman but ran into issues. 

First, GET endpoints don't have a body, so we can't access `req.body.filter` (always undefined). The (only?) way to pass data through a GET request is using URL encoded parameters (e.g., `https://google.com?param1=value1&param2=value2`) which are then accessed through `req.query` in the express endpoint. Now this is a potential problem since passing objects as URL parameters is not easy since it needs to be url-encoded by the frontend and then decoded back into a json object by the backend endpoint. I'm pretty sure it is possible, but it's not ideal.

Another (much simpler) solution would be to just change this endpoint to a POST so that we can pass the filter object in the request body. (this probably violates the REST API guidelines)

Note: the same issue happens with the PATCH endpoint since PATCH requests also don't have a body, apparently.

2021-11-13 19:59 UTC, JoaoPontes98 commented on Service/api/api.js
> +};
Damn thanks for bringing this up because I had no clue about this convention. After some research, it does seem that it is supported for GET requests to have body's but it's not really recommended to do so. ([link](https://stackoverflow.com/questions/978061/http-get-with-request-body)) Below, there's a screenshot of me running the get with a filter, and it does return the two posts with the same title as expected. 

So as far as I can tell, this current implementation does work. but it isn't the way we SHOULD be doing it. To be honest, when developing this, I saw that mongoose had this cool built-in `filter` feature that I thought was an easy way to implement queries with our get. But if we're going to do it right, making an endpoint to query like this should probably be its own ticket in the future.

I'd say to fix this, I could just remove the filter from the get userposts endpoint, and just leave it to return all userposts for now. We could tackle querying using `filter` on a later date.

As for PATCH's not having body's, I think you might be mistaken about that. As far as I can, I'm seeing sources showing that they do have body's. ([link](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/PATCH))

![image](https://user-images.githubusercontent.com/37784969/141657122-d259157a-46c0-4b0e-be4b-5e4e805c93d5.png)

2021-11-13 20:13 UTC, sahilsaini432 commented on Service/api/api.js
> +};
Instead of using query can't we just the data as a `header` in the get request? like this
`const token = req.header('token');`

2021-11-13 20:16 UTC, fredy20501 commented on Service/api/api.js
> +};
Oh, so I guess my problem was just me not understanding how to use postman properly work lol 😅 . 

For the GET body, I did see the same link you gave and I think we're fine keeping it as it is if it works. 
> A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.

Even though the standard says that a GET body doesn't have any defined meaning, since our API is not exposed externally (i.e., only our frontend will use it, it is not something the public will have access to) I think we're fine to deviate from the standard for simplicity.

2021-11-16 15:26 UTC, fredy20501 commented on Service/api/api.js
> +};
The solution decided during the meeting was to change this endpoint to a POST and keep the filter object. (Nathaniel will do it)

2021-11-16 16:29 UTC, nathanielcaron approved these changes

2021-11-16 16:36 UTC, nathanielcaron commented on Service/api/api.js
> +exports.getUserPosts = (req, res) => {
I added a limit of 1,000 posts for now. We can look further into this in a separate ticket:
`DBO-38 Limit and paginate results from post /userposts endpoint`

2021-11-16 16:38 UTC, fredy20501 commented on Service/api/api.js
> +exports.getUserPosts = (req, res) => {
Yep I agree. We'll add pagination later.

2021-11-16 16:39 UTC, fredy20501 approved these changes

2021-11-16 16:42 UTC, merged